export const collections = [
  {
    id: 1,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/collections/1",
    bidLink: "#",
    author: 1,
    previewImg: "/img/collections/sophon/1.png",
    title: "Collection #6949",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 2,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/collections/2",
    bidLink: "#",
    author: 2,
    previewImg: "/img/collections/sophon/2.png",
    title: "Collection #2672",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 3,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/collections/3",
    bidLink: "#",
    author: 3,
    previewImg: "/img/collections/sophon/3.png",
    title: "Collection #2856",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 4,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/collections/4",
    bidLink: "#",
    author: 4,
    previewImg: "/img/collections/sophon/4.png",
    title: "Collection #7643",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 5,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/collections/5",
    bidLink: "#",
    author: 5,
    previewImg: "/img/collections/sophon/5.png",
    title: "Collection #5784",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 6,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/collections/6",
    bidLink: "#",
    author: 6,
    previewImg: "/img/collections/sophon/6.png",
    title: "Collection #0364",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
];
