export const items = [
  {
    id: 1,
    deadline: "December, 30, 2021",
    authorLink: "ItemDetail",
    nftLink: "ItemDetail",
    bidLink: "ItemDetail",
    author: 1,
    previewImg: "/img/items/sophon/1.png",
    title: "Item #2563",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 2,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/items/2",
    bidLink: "#",
    author: 2,
    previewImg: "/img/items/sophon/2.png",
    title: "Item #3637",
    collection: "The Art of Sophon",
    price: "0.06 ETH",
    bid: "1/22",
    likes: 80,
  },
  {
    id: 3,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/items/3",
    bidLink: "#",
    author: 3,
    previewImg: "/img/items/sophon/3.png",
    title: "Item #5547",
    collection: "The Art of Sophon",
    price: "0.05 ETH",
    bid: "1/11",
    likes: 97,
  },
  {
    id: 4,
    deadline: "octorber, 1, 2022",
    authorLink: "#",
    nftLink: "/ItemDetail/items/4",
    bidLink: "#",
    author: 4,
    previewImg: "/img/items/sophon/4.png",
    title: "Item #6815",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 5,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/items/5",
    bidLink: "#",
    author: 5,
    previewImg: "/img/items/sophon/5.png",
    title: "Item #1652",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 6,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/items/6",
    bidLink: "#",
    author: 6,
    previewImg: "/img/items/sophon/6.png",
    title: "Item #8841",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 7,
    deadline: "December, 20, 2021",
    authorLink: "#",
    nftLink: "/ItemDetail/items/7",
    bidLink: "#",
    author: 7,
    previewImg: "/img/items/sophon/7.png",
    title: "Item #5584",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 8,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/items/8",
    bidLink: "#",
    author: 8,
    previewImg: "/img/items/sophon/8.png",
    title: "Item #9763",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 9,
    deadline: "octorber, 3, 2022",
    authorLink: "#",
    nftLink: "/ItemDetail/items/9",
    bidLink: "#",
    author: 9,
    previewImg: "/img/items/sophon/9.png",
    title: "Item #4881",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 10,
    deadline: "octorber, 1, 2022",
    authorLink: "#",
    nftLink: "/ItemDetail/items/10",
    bidLink: "#",
    author: 10,
    previewImg: "/img/items/sophon/10.png",
    title: "item #0637",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 11,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/items/11",
    bidLink: "#",
    author: 11,
    previewImg: "/img/items/sophon/11.png",
    title: "Item #7794",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 12,
    deadline: "octorber, 10, 2022",
    authorLink: "#",
    nftLink: "/ItemDetail/items/12",
    bidLink: "#",
    author: 12,
    previewImg: "/img/items/sophon/12.png",
    title: "Item #2694",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 13,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/items/13",
    bidLink: "#",
    author: 13,
    previewImg: "/img/items/sophon/13.png",
    title: "Item #6949",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
  {
    id: 14,
    deadline: "octorber, 10, 2022",
    authorLink: "#",
    nftLink: "/ItemDetail/items/14",
    bidLink: "#",
    author: 14,
    previewImg: "/img/items/sophon/14.png",
    title: "Item #89763",
    collection: "The Art of Sophon",
    price: "0.08 ETH",
    bid: "1/20",
    likes: 50,
  },
];
