export const slides = [
  {
    id: 1,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/slides/1",
    bidLink: "#",
    author: 1,
    previewImg: "/img/carousel/sophon/1.png",
    title: "Sophon #95623",
    collection: "The Art of Sophon",
    price: "0.05 ETH",
    bid: "1/20",
    likes: 20,
  },
  {
    id: 2,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/slides/2",
    bidLink: "#",
    author: 2,
    previewImg: "/img/carousel/sophon/2.png",
    title: "Sophon #86273",
    collection: "The Art of Sophon",
    price: "0.05 ETH",
    bid: "1/20",
    likes: 20,
  },
  {
    id: 3,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/slides/3",
    bidLink: "#",
    author: 3,
    previewImg: "/img/carousel/sophon/3.png",
    title: "Sophon #73374",
    collection: "The Art of Sophon",
    price: "0.05 ETH",
    bid: "1/20",
    likes: 20,
  },
  {
    id: 4,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/slides/4",
    bidLink: "#",
    author: 4,
    previewImg: "/img/carousel/sophon/4.png",
    title: "Sophon #99763",
    collection: "The Art of Sophon",
    price: "0.05 ETH",
    bid: "1/20",
    likes: 20,
  },
  {
    id: 5,
    deadline: "",
    authorLink: "#",
    nftLink: "/ItemDetail/slides/5",
    bidLink: "#",
    author: 5,
    previewImg: "/img/carousel/sophon/5.png",
    title: "Sophon #89763",
    collection: "The Art of Sophon",
    price: "0.05 ETH",
    bid: "1/20",
    likes: 20,
  },
];
